version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ../:/app

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: airflow-webserver
    depends_on:
      - minio
      - spark
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: foo
    volumes:
      - ../:/opt/airflow
      - ./requirements.txt:/requirements.txt
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      bash -c "pip install -r /requirements.txt &&
               airflow db migrate &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow scheduler & airflow webserver"

volumes:
  minio_data:

